'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class referralprint

    '''<summary>
    '''frmXXChildNameTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXChildNameTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDateEnteredP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDateEnteredP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FrmXXChildName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FrmXXChildName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FrmXXDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FrmXXDOB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXSS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXSex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXCareGiver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXCareGiver As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXCareGiverRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXCareGiverRelationship As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXCareGiverAddFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXCareGiverAddFull As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXPhoneWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXPhoneWork As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXPhoneCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXPhoneCell As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXLGTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXLGTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXLGDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXLGDisplay As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''frmXXLegalCareGiver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXLegalCareGiver As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXLegalCareGiverRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXLegalCareGiverRelationship As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXLGAddFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXLGAddFull As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXlegalPhone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXlegalPhone1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXlegalPhone2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXlegalPhone2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXlegalPhone3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXlegalPhone3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXTypeOfCustodyDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXTypeOfCustodyDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXTypeOfInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXTypeOfInsurance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXRainbowCareYN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXRainbowCareYN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDCPInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDCPInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXNoPlacement9SPY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXNoPlacement9SPY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXCommSpcialConsideration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXCommSpcialConsideration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXAdmAnsNew1YN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXAdmAnsNew1YN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXAdmAnsNew2YN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXAdmAnsNew2YN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXAdmAnsNew3YN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXAdmAnsNew3YN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXAdmAnsNew4YN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXAdmAnsNew4YN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDSMDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDSMDesc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDSMDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDSMDesc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDSMDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDSMDesc3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDSMDesc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDSMDesc4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXDSMDesc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXDSMDesc5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSymtomList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSymtomList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXProblemOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXProblemOther As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXCurrentProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXCurrentProviders As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXCause As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXRefAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXRefAgency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXReferenctInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXReferenctInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXAgencyContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXAgencyContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''frmXXRefEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmXXRefEmail As Global.System.Web.UI.WebControls.Label
End Class
